version: '3.7'

services:
  app:
    image: collection-roulette:latest
    ports:
     - 3000:3000
    # environment:
      # - NODE_ENV=test
    volumes:
      - .\data\files:/app/data/files
      - .\data\db:/app/data/db
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .\data\files:/usr/share/nginx/html