version: '3.7'

services:
  app:
    image: picture-browser:0.0.24
    ports:
     - 3000:3000
    # environment:
      # - NODE_ENV=test
    volumes:
      - D:\Workspaces\picture-browser\data:/app/data
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - D:\Workspaces\picture-browser\data:/usr/share/nginx/html