version: '3.7'

services:
  app:
    image: picture-browser:latest
    ports:
     - 3000:3000
    # environment:
      # - NODE_ENV=test
    volumes:
      - .\data:/app/data
      - .\picture-browser:/app/picture-browser
  web:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - .\data\files:/usr/share/nginx/html