import Head from "next/head";
import path from 'path';
import fs from 'fs';
import styles from '../../styles/Home.module.css'
import Image from "next/image";
import imageSize from "image-size";

export async function getStaticProps({ params }) {

    console.log(params);

    const imgfolder = "photos2";
    const basepath = path.join("public",imgfolder);

    // glob: https://www.npmjs.com/package/glob

    // const files = fs.readdirSync(basepath);
    // const randomFile = Math.floor(Math.random() * files.length);
    // const currentFile = files[randomFile];
    // const currentFile = files[2];

    // const paths = files.map((file) => ({
    //     params: { pid: file }
    // }));

    // const file_paths = files.map((filePath) => {
    //   let rObj = {};
    //   rObj.abs = path.join(basepath, filePath);
    //   rObj.file = filePath;
    //   let dimensions = imageSize(rObj.abs);
    //   rObj.width = dimensions.width;
    //   rObj.height = dimensions.height;
    //   rObj.public = path.posix.join("/","photos", filePath);
    //   return rObj;
    // });
    // console.log(file_paths);


    const publicPath = path.posix.join("/",imgfolder, params.pid);
    const absolutePath = path.join(basepath, params.pid);
    console.log("Absolut path: " + absolutePath); 
    const dimensions = imageSize(absolutePath);

    const img = { 
    //     index: randomFile,
        file: params.pid,
        public: publicPath,
        // absolute: absolutePath,
        dimensions: dimensions
        // address: "/photos/mileena_s_secret_workout__mortal_kombat__by_pactdart_dezd2c2-pre.jpg"
    }

    // console.log(img);    




    return {
        props: {
            img
        }
    };
}

export default function Post({ img }) {
    return (
        <div className={styles.container}>
        <Head>
            <title>Picture Browser</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
            <div style={{padding: "10px", textAlign: "center", height: "90vh", border: 10, borderStyle: 'solid', position: "relative"}}>
            {/* <Image src={currentImage.public} alt="" width={currentImage.width} height={currentImage.height} layout='' objectFit=''></Image> */}
            {/* <Image src="/photos/mileena_s_secret_workout__mortal_kombat__by_pactdart_dezd2c2-pre.jpg" alt="" width={"730px"} height={"1095px"} layout='' objectFit=''></Image> */}
            {/* <Image src={img.public} alt="" width={img.dimensions.width} height={img.dimensions.height} layout='' objectFit=''></Image> */}
            {/* <Image src={img.public} alt="" width={img.dimensions.width} height={img.dimensions.height} layout="fill" objectFit='contain'></Image> */}
            <Image src={img.public} alt="" layout="fill" objectFit='contain'></Image>
            </div>        
            <div style={{ width: "100%", textAlign: "center"}}>
            {/* <div>#{img.index}</div> */}
            <div>
                {/* <Link href={"/post/" + img.file}>
                <a>{img.file}</a>            
                </Link> */}
            </div>

            </div>
        </main>
        </div>
    )
}

export async function getStaticPaths() {
    const imgfolder = "photos2";
    const basepath = path.join("public",imgfolder);

    // glob: https://www.npmjs.com/package/glob

    const files = fs.readdirSync(basepath);
    // const randomFile = Math.floor(Math.random() * files.length);
    // const currentFile = files[randomFile];
    // const currentFile = files[2];

    const paths = files.map((file) => ({
        params: { pid: file }
    }));

    // const file_paths = files.map((filePath) => {
    //   let rObj = {};
    //   rObj.abs = path.join(basepath, filePath);
    //   rObj.file = filePath;
    //   let dimensions = imageSize(rObj.abs);
    //   rObj.width = dimensions.width;
    //   rObj.height = dimensions.height;
    //   rObj.public = path.posix.join("/","photos", filePath);
    //   return rObj;
    // });
    // console.log(file_paths);


    // const publicPath = path.posix.join("/",imgfolder, currentFile);
    // const absolutePath = path.join(basepath, currentFile);
    // console.log("Absolut path: " + absolutePath); 
    // const dimensions = imageSize(absolutePath);

    // const img = { 
    //     index: randomFile,
    //     file: currentFile,
    //     public: publicPath,
    //     absolute: absolutePath,
    //     dimensions: dimensions
    //     // address: "/photos/mileena_s_secret_workout__mortal_kombat__by_pactdart_dezd2c2-pre.jpg"
    // }

    // console.log(img);

    return {
        paths,
        fallback: false
    };
}