import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import ReindexButton from '../components/ReindexButton';

export async function getServerSideProps(context) {

  return {
    props: {}
  };
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Picture Browser</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{textAlign: "center", height: "90vh", position: "relative"}}>
            <Link href="/post/random">
              <a>random</a>            
            </Link>
            <p></p>
            <div>
              <ReindexButton />
            </div>
        </div>        
      </main>
    </div>
  )
}
